name: Actions 😎

on: [push, pull_request]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Set targetPlatform based on branch name
      - name: Set targetPlatform
        id: set-target
        run: |
          declare -A branch_to_platform=(
            ["android"]="Android"
            ["ios"]="iOS"
            ["webgl"]="WebGL"
            ["main"]="StandaloneLinux64"
          )
          branch_name=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')
          platform=${branch_to_platform[$branch_name]}
          if [ -z "$platform" ]; then
            echo "Branch name does not match any known targetPlatform."
            exit 1
          fi
          echo "targetPlatform=$platform" >> $GITHUB_ENV

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ env.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build
